ProjetoLoja/Models/CategoryViewModel/CategoryViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ProjetoLoja.Web.Models.CategoryViewModel
{
    public class CategoryViewModel
    {
        public string Id { get; set; }
        public string Name { get; set; }
    }
}

ProjetoLoja/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using ProjetoLoja.Domain.DTO;
using ProjetoLoja.Services;
using System;
using System.Linq;
using System.Linq.Dynamic.Core;

namespace ProjetoLoja.Web.Controllers
{
    [Authorize(Roles = "ADM")]  
    public class CategoryController : Controller
    {
        private readonly CategoryService _categoryService;

        public CategoryController(CategoryService categoryService)
        {
            _categoryService = categoryService;
        }

        public IActionResult Index() => View();
        
        public IActionResult CreateOrEdit(int id)
        {
            if (id > 0)
            {
                var category = _categoryService.GetById(id);
                return View(category);
            }
            return View();
        }

        [HttpPost]
        public IActionResult CreateOrEdit(CategoryDTO dto)
        {
            bool success = true;
            if (ModelState.IsValid)
                success = _categoryService.Add(dto);
            if (success)
            {
                TempData["Response"] = JsonConvert.SerializeObject(new ResponseDTO(success, "operação realizada com sucesso"));
                return RedirectToAction("Index");
            }
            else
            {
                TempData["Response"] = JsonConvert.SerializeObject(new ResponseDTO(success, "erro na operação"));
                return View();
            }

        }

        public IActionResult DeleteCategory(int categoryId)
        {
            var returnMessage = "registro excluído";
            var errorMessage = "erro ao excluir";
            bool success = true;
            try
            {
                success = _categoryService.Delete(categoryId);
            }
            catch (Exception)
            {
                success = false;
            }
            if (!success)
                returnMessage = errorMessage;
            return Json(new { response = new ResponseDTO(success, returnMessage) });
        }
        public IActionResult GetAllCategories()
        {
            try
            {
                var draw = HttpContext.Request.Form["draw"].FirstOrDefault();

                // Skip number of Rows count  
                var start = Request.Form["start"].FirstOrDefault();

                // Paging Length 10,20  
                var length = Request.Form["length"].FirstOrDefault();

                // Sort Column Name  
                var sortColumn = Request.Form["columns[" + Request.Form["order[0][column]"].FirstOrDefault() + "][name]"].FirstOrDefault();

                // Sort Column Direction (asc, desc)  
                var sortColumnDirection = Request.Form["order[0][dir]"].FirstOrDefault();

                // Search Value from (Search box)  
                var searchValue = Request.Form["search[value]"].FirstOrDefault();

                //Paging Size (10, 20, 50,100)  
                int pageSize = length != null ? Convert.ToInt32(length) : 0;

                int skip = start != null ? Convert.ToInt32(start) : 0;

                int recordsTotal = 0;

                // getting all Customer data  
                var customerData = _categoryService.GetAll();
                //Sorting  
                if (!(string.IsNullOrEmpty(sortColumn) && string.IsNullOrEmpty(sortColumnDirection)))
                {
                    customerData = customerData.OrderBy(sortColumn + " " + sortColumnDirection);
                }
                //Search  
                if (!string.IsNullOrEmpty(searchValue))
                {
                    customerData = customerData.Where(m => m.Name.Contains(searchValue.Trim()));
                }

                //total number of rows counts   
                recordsTotal = customerData.Count();
                //Paging   
                var data = customerData.Skip(skip).Take(pageSize).ToList();
                //Returning Json Data  
                return Json(new { draw, recordsFiltered = recordsTotal, recordsTotal, data });
            }
            catch (Exception)
            {
                throw;
            }
        }
    }
}

ProjetoLoja/Views/Category/CreateOrEdit.cshtml
@model ProjetoLoja.Domain.DTO.CategoryDTO

@{
    ViewData["Title"] = "Gerenciamento de Categorias";
}

<h2>Gerenciamento de Categorias</h2>

<h4>Categoria</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateOrEdit" id="formCategory">
            <input type="hidden" asp-for="Id" id="hdnId" />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <button type="submit" id="btnAddCategory" class="btn btn-outline btn-outline-success btn-lg">
                    <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
                    <span id="btnAddCategoryText">Cadastrar</span>
                </button>
                <button type="button" id="btnBack" class="btn btn-outline btn-outline-secondary btn-lg" onclick="location.href='@Url.Action("Index", "Category")'">
                    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span> Voltar
                </button>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script src="~/js/category/createOrEdit.js"></script>
}

ProjetoLoja/Views/Category/Index.cshtml
@model List<ProjetoLoja.Domain.DTO.CategoryDTO>

@{
    ViewData["Title"] = "Index";
}

<div class="container">
    <div class="row line-height-60">
        <div class="col-md-9"><h2>Categorias</h2></div>
        <div class="col-md-3 align-right pull-left">
            <button type="button" class="btn btn-outline btn-outline-success btn-lg" onclick="location.href='@Url.Action("CreateOrEdit", "Category")'">
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Nova Categoria
            </button>
        </div>
    </div>
</div>

<div class="container">
    <br />
    <div style="width:100%; margin:0 auto;">
        <table id="categoriesDT" class="table table-striped table-bordered dt-responsive nowrap" width="100%" cellspacing="0">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Nome</th>
                    <th>Editar</th>
                    <th>Excluir</th>
                </tr>
            </thead>
        </table>
    </div>
</div>

<!-- Modal Delete -->
<div class="modal fade" id="deleteCategoryModal" tabindex="-1" role="dialog" aria-labelledby="deleteCategoryModal" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            @*<div class="modal-header"></div>*@
            <div class="modal-body">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="exampleModalLongTitle">Deseja Realmente Excluir?</h4>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Não</button>
                <button type="button" class="btn btn-primary" id="btnConfirmModal">Sim</button>
            </div>
        </div>
    </div>
</div>

<!-- Modal Message -->
<div class="modal fade" id="messageModal" tabindex="-1" role="dialog" aria-labelledby="messageModal" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-body">
                <span id="spanMessageModal"></span>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
            </div>
        </div>
    </div>
</div>


@section Scripts
{
    <script>
        Response = null;
        @if (TempData["Response"] != null) { 
            @:Response = @Html.Raw(TempData["Response"]);        
        }
    </script>
    <script src="~/js/category/index.js"></script>
}